# config/packages/cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_methods: ['POST']
        allow_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/': ~
